
import java.io.BufferedWriter;
import java.lang.String;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manav, Himanshu, Jimil
 */
public class Pizza extends javax.swing.JFrame {
    int x=1;
    /**
     * Creates new form Pizza
     */
    public Pizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jMenu2 = new javax.swing.JMenu();
        labelFarmFrenzy = new java.awt.Label();
        labelPeperoni = new java.awt.Label();
        labelMexicana = new java.awt.Label();
        labelItalianGiant = new java.awt.Label();
        labelSpicyIndian = new java.awt.Label();
        labelSpecialPaneer = new java.awt.Label();
        jComboBoxMexicana = new javax.swing.JComboBox<>();
        jComboBoxItalianGiant = new javax.swing.JComboBox<>();
        jComboBoxSpicyIndian = new javax.swing.JComboBox<>();
        jComboBoxSpecialPaneer = new javax.swing.JComboBox<>();
        jComboBoxFarmFrenzy = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabelPay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPeperoni = new javax.swing.JTextField();
        jTextFieldMexicana = new javax.swing.JTextField();
        jTextFieldFarmFrenzy = new javax.swing.JTextField();
        jTextFieldItalianGiant = new javax.swing.JTextField();
        jTextFieldSpicyIndian = new javax.swing.JTextField();
        jTextFieldSpecialPaneer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jComboBoxPeperoni = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldPay = new javax.swing.JTextField();
        jButtonPrint = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelFarmFrenzy.setText("Farm Frenzy");

        labelPeperoni.setText("Peperoni");

        labelMexicana.setText("Mexicana");

        labelItalianGiant.setText("Italian giant");

        labelSpicyIndian.setText("Spicy Indian");

        labelSpecialPaneer.setText("Special Paneer");

        jComboBoxMexicana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Small", "Medium", "Large" }));
        jComboBoxMexicana.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxMexicana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBoxItalianGiant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Small", "Medium", "Large" }));
        jComboBoxItalianGiant.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxItalianGiant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBoxSpicyIndian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Small", "Medium", "Large" }));
        jComboBoxSpicyIndian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxSpicyIndian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBoxSpecialPaneer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Small", "Medium", "Large" }));
        jComboBoxSpecialPaneer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxSpecialPaneer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBoxFarmFrenzy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Small", "Medium", "Large" }));
        jComboBoxFarmFrenzy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxFarmFrenzy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pizza Ordering System");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)))))
        );

        jTable.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Size", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
            jTable.getColumnModel().getColumn(1).setResizable(false);
            jTable.getColumnModel().getColumn(2).setResizable(false);
            jTable.getColumnModel().getColumn(3).setResizable(false);
            jTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabelPay.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabelPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPay.setText("Grand Total");
        jLabelPay.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Size");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Qty.");

        jTextFieldPeperoni.setText("0");
        jTextFieldPeperoni.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPeperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeperoniActionPerformed(evt);
            }
        });

        jTextFieldMexicana.setText("0");
        jTextFieldMexicana.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldFarmFrenzy.setText("0");
        jTextFieldFarmFrenzy.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldItalianGiant.setText("0");
        jTextFieldItalianGiant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldSpicyIndian.setText("0");
        jTextFieldSpicyIndian.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldSpecialPaneer.setText("0");
        jTextFieldSpecialPaneer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Price");

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText(" Small - 200");

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText(" Medium - 300");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText(" Large - 500");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jComboBoxPeperoni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Small", "Medium", "Large" }));
        jComboBoxPeperoni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxPeperoni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonAdd.setBackground(new java.awt.Color(0, 204, 255));
        jButtonAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAdd.setText("ADD");
        jButtonAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jButtonAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonAddKeyTyped(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(0, 204, 255));
        jButtonDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTextFieldPay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPayActionPerformed(evt);
            }
        });

        jButtonPrint.setBackground(new java.awt.Color(102, 255, 0));
        jButtonPrint.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonPrint.setText("PRINT");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(305, 305, 305)
                                .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelSpecialPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxSpecialPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSpecialPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(labelFarmFrenzy, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                                    .addComponent(labelMexicana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(labelItalianGiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(labelSpicyIndian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBoxSpicyIndian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBoxItalianGiant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBoxMexicana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBoxFarmFrenzy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(labelPeperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboBoxPeperoni, 0, 80, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldPeperoni, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(jTextFieldFarmFrenzy, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(jTextFieldMexicana, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(jTextFieldItalianGiant, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(jTextFieldSpicyIndian, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldPay, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldPeperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxPeperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelPeperoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFarmFrenzy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxFarmFrenzy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldFarmFrenzy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxMexicana, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldMexicana, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelMexicana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxItalianGiant, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItalianGiant, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelItalianGiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSpicyIndian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSpicyIndian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSpicyIndian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSpecialPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxSpecialPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSpecialPaneer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel3)))
                        .addGap(2, 2, 2)))
                .addGap(41, 41, 41)
                .addComponent(jLabelPay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jTextFieldPeperoniActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            int peperoniQty = Integer.parseInt(jTextFieldPeperoni.getText());
            if (peperoniQty < 0) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                jTextFieldPeperoni.setText("0");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            jTextFieldPeperoni.setText("0");
        }
    }
    

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int quantity = Integer.parseInt(jTextField4.getText());
            if (quantity < 0) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                jTextField4.setText("0");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            jTextField4.setText("0");
    }
    }

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int quantity = Integer.parseInt(jTextField10.getText());
            if (quantity < 0) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                jTextField10.setText("0");
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            jTextField10.setText("0");
        }
    }
    
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable.getModel();
        String Peperoni= jComboBoxPeperoni.getSelectedItem().toString();//gets the size of pizza
        int PeperoniQty=Integer.parseInt(jTextFieldPeperoni.getText());//gets the Quantity of pizza
        if((!(Peperoni.equals("None"))) && PeperoniQty!=0)
        {
            int price;//sets price according to size of pizza
            if(Peperoni.equals("Small"))
                price=200;
            else if(Peperoni.equals("Medium"))
                price=300;
            else
                price=500;
            int total=price*PeperoniQty;//gives total for that pizza
            model.addRow(new Object[]{labelPeperoni.getText(),Peperoni,price,PeperoniQty,total});
        }
        String Farm= jComboBoxFarmFrenzy.getSelectedItem().toString();//gets the size of pizza
        int FarmQty=Integer.parseInt(jTextFieldFarmFrenzy.getText());//gets the Quantity of pizza
        if((!(Farm.equals("None"))) && FarmQty!=0)
        {
            int price;//sets price according to size of pizza
            if(Farm.equals("Small"))
                price=200;
            else if(Farm.equals("Medium"))
                price=300;
            else
                price=500;
            int total=price*FarmQty;//gives total for that pizza
            model.addRow(new Object[]{labelFarmFrenzy.getText(),Farm,price,FarmQty,total});
        }
        String Mexicana= jComboBoxMexicana.getSelectedItem().toString();//gets the size of pizza
        int MexicanaQty=Integer.parseInt(jTextFieldMexicana.getText());//gets the Quantity of pizza
        if((!(Mexicana.equals("None"))) && MexicanaQty!=0)
        {
            int price;//sets price according to size of pizza
            if(Mexicana.equals("Small"))
                price=200;
            else if(Mexicana.equals("Medium"))
                price=300;
            else
                price=500;
            int total=price*MexicanaQty;//gives total for that pizza
            model.addRow(new Object[]{labelMexicana.getText(),Mexicana,price,MexicanaQty,total});
        } 
        String ItalianGiant= jComboBoxItalianGiant.getSelectedItem().toString();//gets the size of pizza
        int ItalianGiantQty=Integer.parseInt(jTextFieldItalianGiant.getText());
        if((!(ItalianGiant.equals("None"))) && ItalianGiantQty!=0)
        {
            int price;//sets price according to size of pizza
            if(ItalianGiant.equals("Small"))
                price=200;
            else if(ItalianGiant.equals("Medium"))
                price=300;
            else
                price=500;
            int total=price*ItalianGiantQty;//gives total for that pizza
            model.addRow(new Object[]{labelItalianGiant.getText(),ItalianGiant,price,ItalianGiantQty,total});
        } 
        String SpicyIndian= jComboBoxSpicyIndian.getSelectedItem().toString();//gets the size of pizza
        int SpicyIndianQty=Integer.parseInt(jTextFieldSpicyIndian.getText());//gets the Quantity of pizza
        if((!(SpicyIndian.equals("None"))) && SpicyIndianQty!=0)
        {
            int price;//sets price according to size of pizza
            if(SpicyIndian.equals("Small"))
                price=200;
            else if(SpicyIndian.equals("Medium"))
                price=300;
            else
                price=500;
            int total=price*SpicyIndianQty;//gives total for that pizza
            model.addRow(new Object[]{labelSpicyIndian.getText(),SpicyIndian,price,SpicyIndianQty,total});
        }
        String SpecialPaneer= jComboBoxSpecialPaneer.getSelectedItem().toString();//gets the size of pizza
        int SpecialPaneerQty=Integer.parseInt(jTextFieldSpecialPaneer.getText());//gets the Quantity of pizza
        if((!(SpecialPaneer.equals("None"))) && SpecialPaneerQty!=0)
        {
            int price;//sets price according to size of pizza
            if(SpecialPaneer.equals("Small"))
                price=200;
            else if(SpecialPaneer.equals("Medium"))
                price=300;
            else
                price=500;
            int total=price*SpecialPaneerQty;//gives total for that pizza
            model.addRow(new Object[]{labelSpecialPaneer.getText(),SpecialPaneer,price,SpecialPaneerQty,total});
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAddKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddKeyTyped
    //delete button
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tblModel = (DefaultTableModel) jTable.getModel();
        // delete row
        if (jTable.getSelectedRowCount()==1){
            // if single row is selected than delete
            tblModel.removeRow(jTable.getSelectedRow());
        }
        else{
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "List is Empty");
            }
            else{
                JOptionPane.showMessageDialog(this, "Please select single Row for delete");
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    //Printing using File i/o
    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model=(DefaultTableModel)jTable.getModel();
        int Total=0;
        for(int i=0;i<Model.getRowCount();i++)
        {
            Total += ((int)Model.getValueAt(i,4));
        }
        jTextFieldPay.setText(Integer.toString(Total));
        try {
        File file=new File("D:\\3rd Sem\\OOP\\Innovative assignment\\Pizza\\src\\main\\java\\Receipt.txt");
        FileWriter fw=new FileWriter(file);
        BufferedWriter bw=new BufferedWriter(fw);
        bw.write("Receipt No. "+x);
        x++;
        bw.write("\nName\t\tSize\tPrice\tQuantity\tTotal\n");
        for(int i=0;i<jTable.getRowCount();i++)
        {
            for(int j=0;j<jTable.getColumnCount();j++)
            {
                if(j==(jTable.getColumnCount()-1))
                    bw.write("\t");
                bw.write(jTable.getValueAt(i,j).toString()+"\t");
            }
            bw.write("\n");
        }
        bw.write("\nGrand Total - "+Total);
        bw.close();
        }
        catch(IOException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jTextFieldPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPayActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JComboBox<String> jComboBoxFarmFrenzy;
    private javax.swing.JComboBox<String> jComboBoxItalianGiant;
    private javax.swing.JComboBox<String> jComboBoxMexicana;
    private javax.swing.JComboBox<String> jComboBoxPeperoni;
    private javax.swing.JComboBox<String> jComboBoxSpecialPaneer;
    private javax.swing.JComboBox<String> jComboBoxSpicyIndian;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPay;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldFarmFrenzy;
    private javax.swing.JTextField jTextFieldItalianGiant;
    private javax.swing.JTextField jTextFieldMexicana;
    private javax.swing.JTextField jTextFieldPay;
    private javax.swing.JTextField jTextFieldPeperoni;
    private javax.swing.JTextField jTextFieldSpecialPaneer;
    private javax.swing.JTextField jTextFieldSpicyIndian;
    private java.awt.Label labelFarmFrenzy;
    private java.awt.Label labelItalianGiant;
    private java.awt.Label labelMexicana;
    private java.awt.Label labelPeperoni;
    private java.awt.Label labelSpecialPaneer;
    private java.awt.Label labelSpicyIndian;
    // End of variables declaration//GEN-END:variables
}
